/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Huong' at '17/02/16 10:20' with Gradle 2.6
 *
 * @author Huong, @date 17/02/16 10:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
